name: CI

on:
  pull_request:
  push:
    branches: [main]

permissions:
  contents: read

jobs:
  check:
    runs-on: macos-14
    timeout-minutes: 30
    steps:
      - uses: actions/checkout@v7
      - uses: totto2727-org/monorepo/.github/actions/setup-nix@main
      - name: Check the Rust project
        run: nix develop --command just ci
